services:
  app:
    build:
      context: .
      dockerfile: alvie-cli/Dockerfile
    
    hostname: alvie-cli

    volumes:
      - .:/home/alvie/alvie-cli

    working_dir: /home/alvie/alvie-cli
    stdin_open: true
    tty: true
    # activate venv
    command: /bin/bash --rcfile /home/alvie/venv/bin/activate
  viewer:
    build:
      context: ./alvie-viewer
      dockerfile: Dockerfile

    hostname: alvie-viewer

    ports:
      - "127.0.0.1:4242:80"