services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    hostname: alvie-cli

    volumes:
      - .:/home/alvie/alvie-cli

    working_dir: /home/alvie/alvie-cli
    stdin_open: true
    tty: true
    # activate venv
    command: /bin/bash --rcfile /home/alvie/venv/bin/activate